version: '3'

services:
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: avaliacao
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432